title: "Student Portfolio"
description: "A modern student portfolio showcasing projects, skills, and blog posts"
name: "Your Name"
role: "Computer Science Student & Developer"
hero_bg: "/images/hero-background.jpg"
